### PR TITLE
Don't change custom fields encryption flag on update

### LINKED ISSUE #5591: Changing an encrypted custom text field leads to field losing it's encryption
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

Bug Description:
Changing an encrypted custom text field leads to field losing it's encryption

**To Reproduce**
1. Go to 'custom fields' and create a encrypted custom field of the type 'text'
2. Assign custom field to assets
3. Open an asset and insert a value into the custom field (the custom field is now readable for all user with corresponding roles)
4. Go to 'custom fields' and change the name of the newly created field.
5. The field is now readable by all users and shows the encrypted value

6. (Remedy) in sql: change the value 'field_encryption' for the custom field from 0 to 1 

*Expected behavior**
The custom field should stay encrypted after a change.

**Server (please complete the following information):**
 - Snipe-IT Version v4.1.11-pre - build 3307 (master)
 - OS: Debian 8 Jessie
 - Web Server: Apache
 - 7.2.2

**Desktop (please complete the following information):**
 - OS: Windows 7 
 - Browser: Chrome
 - Version: 66.0.3359.181

Note:
I'm totally aware that a name change of a custom field should not to be lightly done, but the change was made "by mistake".

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/58770272-changing-an-encrypted-custom-text-field-leads-to-field-losing-it-s-encryption?utm_campaign=plugin&utm_content=tracker%2F505106&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F505106&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by tilldeeke**
This PR removes the ability to change the "field_encrypted" flag on updating a custom field.
That should prevent the custom fields value to ever change from "encrypted" to "not encrypted".

This fixes #5591.

### CODE REVIEW

**Comment by snipe** [comment]
That seems pretty straightforward - did you get a chance to test this out?

**Comment by tilldeeke** [comment]
I tested the UI part manually by creating a custom field, setting its value in an asset and then changing the name of the custom field. That works as expected, not changing the flag. The same with unencrypted fields.

The API part _should_ work, since the validation roles for custom fields only require the field "field_encrypted" to be "nullable|boolean", so the field doesn't have to be present.

I'd like to write tests covering this to be sure, but I'm unfamiliar with codeception. I'll be reading up on that over the weekend and will update this PR with appropriate tests if thats alright with you :)

**Comment by snipe** [comment]
> The API part should work, since the validation roles for custom fields only require the field "field_encrypted" to be "nullable|boolean", so the field doesn't have to be present.

It's not required, but I'd bet if someone includes it, it will allow them to (intentionally or not) change whether or not the field is encrypted, which could cause problems. We might want to pull that out of update method for the API, lest we have differing behavior that confuses folks.

I wouldn't worry about the Codeception part - we use that mostly for BDD (and I can never get the damned tests to work locally - and if I do, then they don't work on travis anymore. Argh.) But maybe just a small set of unit test (which uses phpunit, it's just wrapped in the Codeception process)

File: app/Http/Controllers/Api/CustomFieldsController.php [hunk 1]
```diff
@@ -59,7 +59,13 @@ public function update(Request $request, $id)
...
         $this->authorize('edit', CustomField::class);
         $field = CustomField::findOrFail($id);
-        $data = $request->all();
+        
+        /**
+         * Updated values for the field, 
+         * without the "field_encrypted" flag, preventing the change of encryption status
+         * @var array
+         */
+        $data = $request->except(['field_encrypted']);
```
Comment (tilldeeke) [inline app/Http/Controllers/Api/CustomFieldsController.php]: > It's not required, but I'd bet if someone includes it, it will allow them to (intentionally or not) change whether or not the field is encrypted, which could cause problems.

That should be prevented by this line, even if somebody includes `field_encrypted=1` on their request, it will be stripped from the `data` array, so the `$field->fill($data);` later would never contain the flag.

Comment (snipe) [reply app/Http/Controllers/Api/CustomFieldsController.php]: Derp. Yep, you're right - I hadn't noticed that you included the API controller in there. (It's very late here, and I am a little dumb right now... )

**Comment by snipe** [comment]
tip-hat

**Comment by snipe** [comment]
I should also warn you - I'm about to start pushing stuff into a new branch for the Laravel v5.6 + PHP7+ stuff which might get a little messy. I'm trying to tie up all lose end PRs right now so that contributors don't get screwed over (or so that I don't have to spend hours and hours fixing the PRs that are conflicting all over the place because of the framework upgrade.) I'm hoping I can just merge the feature branches into the new branch, but I don't know how tenable that will be. Folks don't always tell me before they push out a big PR.

File: app/Http/Controllers/Api/CustomFieldsController.php (hunk 1 above)
Comment (tilldeeke) [reply app/Http/Controllers/Api/CustomFieldsController.php]: No problem! I made #5815 when it was like 3am here, I know the feeling! 😄

**Comment by tilldeeke** [comment]
Thanks for the heads up! I have some issues I'd like to work on, so if they require more than 1-2 lines of code, should I wait till you finished the stuff in the branch?

**Comment by tilldeeke** [comment]
> I feel like most things shouldn't affect you, as long as your code works with PHP7.

Ahh, okay! I'm running Homestead with PHP 7.2, so that should not be a problem.

If I can help you in any way, I'm more than happy to!

**Comment by snipe** [comment]
Thanks! There's a lot I want to do for the next version (it gets a little overwhelming, TBH) but all of them are waiting on the framework upgrade, and I already did all that work once, so I just have to selectively merge it back or try rebasing and hoping for the best. It should go pretty smoothly 🤞 . Famous last words, right?

 Once the framework is upgraded, we can start to tackle things like:

- Traits for all the things to unify and expand common behaviors across items:
   - requestable
   - checkout-to-able to potentially unify some of the tables
   - making asset models and accessory/etc types work more similarly (min amount of x assets of type y model, alerts when asset inventory is low)
   - MAYBE customfieldable tho I am loathe to just start randomly letting people add all kinds of columns
   -  and so on...
- Converting everything over to Flysystem for uploads so users (and us) can use signed S3 buckets (or whatever they want) natively. (We'll need a file migrator script for that too, but I've written those before and it's not bad.)

None of these things are particularly exciting from the end-user's perspective, but they'll put us in a better place to have cleaner code to work from moving forward.

There are two things that are basically preventing me from working on those things right now:

- https://github.com/snipe/snipe-it/issues/5470
- https://github.com/snipe/snipe-it/issues/5772

Both of these are regressions, and they need to be fixed before we can move forward with the new hotness. If you have any desire to take a stab at either of those, that would be awesome. If not, I totally understand. They're not exactly exciting issues to work on.
