### PR TITLE
FIXED: #13844 Adds Webhook and Mail Notifications for Components

### LINKED ISSUE #13844: Is slack integration (webhook notification) not work on components check in or out?
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I am using slack integration (webhook notification).
It works where on Assets, Licenses, Accessories, Consumables check in or out.
But it is not working on Components only.

When it works (in check in or out at assets, licenses, accessories, consumables page)
スクリーンショット 2023-11-07 16 51 55

It is not working (components)
スクリーンショット 2023-11-07 16 53 05

[Documents](https://snipe-it.readme.io/docs/slack-integration)

> Snipe-IT allows integration with Slack, which will allow you to get notifications to a specified Slack channel when someone checks an asset, license, component or consumable in or out.

Is this valid?

Best regards.

### Reproduction steps

1. open components page
2. select checkout

### Expected behavior

slack integration is working too in components.

### Screenshots

_No response_

### Snipe-IT Version

v6.2.3 - build 11936 (master)

### Operating System

Rocky linux 8

### Web Server

Nginx

### PHP Version

8.1.6

### Operating System

_No response_

### Browser

_No response_

### Version

_No response_

### Device

_No response_

### Operating System

_No response_

### Browser

_No response_

### Version

_No response_

### Error messages

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Godmartinz**
This adds Component Notifications and Mail markdowns and mailables and webhook methods.
Google:
image
MS Teams:
image
Slack:
image

Updates the checkout form to convey if a copy of the EULA, webhook  notification, or acceptance link will be sent.
image
Checkout Mail:
image

Checkin Mail:
image

Also adds test around component checkin/out notifications.
`requireAcceptance()` and `getEula()` were not present on the Component Model, so they were added as well.

Fixes: #13844

### CODE REVIEW

File: app/Mail/CheckoutComponentMail.php [hunk 1]
```diff
@@ -26,7 +26,7 @@ public function __construct(Component $component, $checkedOutTo, User $checkedOu
         $this->note = $note;
         $this->target = $checkedOutTo;
         $this->acceptance = $acceptance;
-        $this->qty = optional($component->assets->first())->pivot->assigned_qty;
+        $this->qty = optional(optional($component->assets->first())->pivot)->assigned_qty;
```
Comment (snipe) [inline app/Mail/CheckoutComponentMail.php]: Why do we need two `optional`s here?

Comment (Godmartinz) [reply app/Mail/CheckoutComponentMail.php]: yea, I rewrote that with ternaries instead.

**Comment by snipe** [comment]
The email notification is just for the admin user? (You cannot check components out to people, so that would be the only thing that makes sense here.)

**Comment by Godmartinz** [comment]
@snipe if the component is being assigned to an unassigned asset, no email is sent unless there is a CC email filled in the settings. but If a component is being assigned to an assigned asset an email is sent to that User--if it is a user with an email. 
Thats how we want it, no?
