### PR TITLE
Revision of #5471

### LINKED ISSUE #5471: Search not working for the list view of users displayed in Accessory
#### Please confirm you have done the following before posting your bug report:

**Describe the bug**
Search not working for the list view of users displayed in Accessory

**Expected behavior**
When we look for any user in a search bar it should pick the user in the list, but nothing happens when we search. 

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/57895158-search-not-working-for-the-list-view-of-users-displayed-in-accessory?utm_campaign=plugin&utm_content=tracker%2F505106&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F505106&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by inietov**
Fixed #5471. A better solution than the last using collections methods. Now Querying the established relation between Accessory and User

### CODE REVIEW

File: app/Http/Controllers/Api/AccessoriesController.php [hunk 1]
```diff
@@ -143,13 +143,16 @@ public function checkedout($id, Request $request)
 
         $accessory->lastCheckoutArray = $accessory->lastCheckout->toArray();
         $accessory_users = $accessory->users;
-
-        if($request->filled('search')){
-            $accessory_users = $accessory_users->where('first_name', $request->input('search'))->concat($accessory_users->where('last_name', $request->input('search')));
+        
+        if ($request->filled('search')) {
+            $accessory_users = Accessory::find(1)->users()
```
Comment (dmeltzer) [inline app/Http/Controllers/Api/AccessoriesController.php]: This should use $accessory->users() correct? Currently you're searching against an accessory with a specific id.

Comment (inietov) [reply app/Http/Controllers/Api/AccessoriesController.php]: Ugh, yeah sorry... I actually tried to use  'Accessory::find($id)->users()' but I let the magic number behind. Your solution looks better, thank you.

**Comment by snipe** [comment]
community-thankyou
