### PR TITLE
Fixed #6834 and #6402 - use inline QR code generation for 2FA

### LINKED ISSUE #6834: Google Authenticator
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**

I turned on the option google auth and then I got logged out. Now when I try to login It should show a code for me to scan but I dont see anything. So now I am basicly locked out of snipeit?
[
a4aeba1d42c86fbae8bc37c8a889d366
](url)

### PR DESCRIPTION
**Pull request by snipe**
- Updated the package to use latest `pragmarx/google2fa` and added `pragmarx/google2fa-laravel`. We do not use most of the laravel package, but to keep this PR small, it was the cleanest path, as the newer versions of the package do not include the laravel classes/facades
- Use the barcode library we're already using for asset tags to generate the enrollment QR
- Updated login controller to use translation strings

### CODE REVIEW

File: app/Http/Controllers/Auth/LoginController.php [hunk 1]
```diff
@@ -240,6 +240,16 @@ public function getTwoFactorEnroll()
      */
     public function getTwoFactorAuth()
     {
+        if (!Auth::check()) {
```
Comment (uberbrady) [inline app/Http/Controllers/Auth/LoginController.php]: This feels like it's doing more than what it says it's supposed to do.

It seems that _if_ this function gets called, *and* either the `two_factor_secret` is blank, or the `two_factor_enrolled` is not enabled - then we bounce you to `two-factor-enroll`.

So I'm assuming this function only gets called if 2fa is enabled or something? I'm not sure. But maybe we can either rename this or move the logic around so it doesn't feel like something else is making the decision about how to call this. Or, we can document how this works and under what circumstances it's being called in?

Comment (snipe) [reply app/Http/Controllers/Auth/LoginController.php]: > So I'm assuming this function only gets called if 2fa is enabled or something?

We have middleware that forces that redirect if necessary. 
https://github.com/snipe/snipe-it/blob/master/app/Http/Middleware/CheckForTwoFactor.php

That's there just in case you have a browser history/etc situation. You wouldn't normally find yourself on that page if the the middleware conditions weren't met.
